#ifndef INC_D3ColumnPermissionBase_H
#define INC_D3ColumnPermissionBase_H

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can gegenerate this file.
//
// The file declares methods which simplify client interactions with objects of type 
// D3ColumnPermission representing instances of D3MDDB.D3ColumnPermission.
//
//       For D3 to work correctly, you must implement your own class as follows:
//
//       #include "D3ColumnPermissionBase.h"
//
//       namespace D3
//       {
//         class D3ColumnPermission : public D3ColumnPermissionBase
//         {
//           D3_CLASS_DECL(D3ColumnPermission);
//
//           protected:
//             D3ColumnPermission() {}
//
//           public:
//             ~D3ColumnPermission() {}
//
//             // Insert your specialised member functions here...
//
//         };
//       } // end namespace D3
//

#include "Entity.h"
#include "Column.h"
#include "Key.h"
#include "Relation.h"
#include "D3MDDB.h"

namespace D3
{

	//! Use these enums to access columns through D3ColumnPermission::Column() method
	enum D3ColumnPermission_Fields
	{
		D3ColumnPermission_RoleID,
		D3ColumnPermission_MetaColumnID,
		D3ColumnPermission_AccessRights
	};


	//! D3ColumnPermissionBase is a base class that \b MUST be subclassed through a class called \a D3ColumnPermission.
	/*! The purpose of this class to provide more natural access to related objects as well as this' columns.
			This class is only usefull if it is subclassed by a class called D3ColumnPermission
			Equally important is that the meta dictionary knows of the existence of your subclass as well as
			specialised Relation classes implemented herein. Only once these details have been added to the
			dictionary will D3 instantiate objects of type \a D3ColumnPermission representing rows from the table \a D3MDDB.D3ColumnPermission.
	*/
	class D3_API D3ColumnPermissionBase: public Entity
	{
		D3_CLASS_DECL(D3ColumnPermissionBase);

		public:
			//! Enable iterating over all instances of this
			class D3_API iterator : public InstanceKeyPtrSetItr
			{
				public:
					iterator() {}
					iterator(const InstanceKeyPtrSetItr& itr) : InstanceKeyPtrSetItr(itr) {}

					//! De-reference operator*()
					virtual D3ColumnPermissionPtr   operator*();
					//! Assignment operator=()
					virtual iterator&               operator=(const iterator& itr);
			};

			static unsigned int                 size(DatabasePtr pDB)         { return GetAll(pDB)->size(); }
			static bool                         empty(DatabasePtr pDB)        { return GetAll(pDB)->empty(); }
			static iterator                     begin(DatabasePtr pDB)        { return iterator(GetAll(pDB)->begin()); }
			static iterator                     end(DatabasePtr pDB)          { return iterator(GetAll(pDB)->end()); }



		protected:
			D3ColumnPermissionBase() {}

		public:
			~D3ColumnPermissionBase() {}

			//! Create a new D3ColumnPermission
			static D3ColumnPermissionPtr        CreateD3ColumnPermission(DatabasePtr pDB)		{ return (D3ColumnPermissionPtr) pDB->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3ColumnPermission)->CreateInstance(pDB); }

			//! Return a collection of all instances of this
			static InstanceKeyPtrSetPtr					GetAll(DatabasePtr pDB);

			//! Load all instances of this
			static void													LoadAll(DatabasePtr pDB, bool bRefresh = false, bool bLazyFetch = true);

			//! Load a particular instance of this
			static D3ColumnPermissionPtr        Load(DatabasePtr pDB, long lRoleID, long lMetaColumnID, bool bRefresh = false, bool bLazyFetch = true);

			//! Get related parent D3Role object
			virtual D3RolePtr                   GetD3Role();
			//! Set related parent D3Role object
			virtual void												SetD3Role(D3RolePtr pD3Role);
			//! Get related parent D3MetaColumn object
			virtual D3MetaColumnPtr             GetD3MetaColumn();
			//! Set related parent D3MetaColumn object
			virtual void												SetD3MetaColumn(D3MetaColumnPtr pD3MetaColumn);


			/*! @name Get Column Values
			    \note These accessors do not throw even if the column's value is NULL.
			           Therefore, you should use these methods only if you're sure the
			           column's value is NOT NULL before using these.
			*/
			//@{
			//! RoleID
			virtual long                        GetRoleID()                    { return Column(D3ColumnPermission_RoleID)->GetLong(); }
			//! MetaColumnID
			virtual long                        GetMetaColumnID()              { return Column(D3ColumnPermission_MetaColumnID)->GetLong(); }
			//! AccessRights
			virtual long                        GetAccessRights()              { return Column(D3ColumnPermission_AccessRights)->GetLong(); }
			//@}

			/*! @name Set Column Values
			*/
			//@{
			//! Set RoleID
			virtual bool												SetRoleID(long val)            { return Column(D3ColumnPermission_RoleID)->SetValue(val); }
			//! Set MetaColumnID
			virtual bool												SetMetaColumnID(long val)      { return Column(D3ColumnPermission_MetaColumnID)->SetValue(val); }
			//! Set AccessRights
			virtual bool												SetAccessRights(long val)      { return Column(D3ColumnPermission_AccessRights)->SetValue(val); }
			//@}

			//! A column accessor provided mainly for backwards compatibility
			virtual ColumnPtr										Column(D3ColumnPermission_Fields eCol){ return Entity::GetColumn((unsigned int) eCol); }
	};



} // end namespace D3


#endif /* INC_D3ColumnPermissionBase_H */
