// MODULE: D3DatabasePermissionBase.cpp
//;
//; IMPLEMENTATION CLASS: D3DatabasePermissionBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3DatabasePermissionBase.h"

// Dependent includes
//
#include "D3MetaDatabaseBase.h"
#include "D3RoleBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3DatabasePermissionBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3DatabasePermissionBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3DatabasePermissionBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3DatabasePermission)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3DatabasePermissionBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3DatabasePermission)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3DatabasePermissionPtr D3DatabasePermissionBase::Load(DatabasePtr pDB, long lRoleID, long lMetaDatabaseID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3DatabasePermission)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3DatabasePermission_RoleID)->SetValue(lRoleID);
		tmpKey.GetColumn(D3MDDB_D3DatabasePermission_MetaDatabaseID)->SetValue(lMetaDatabaseID);

		return (D3DatabasePermissionPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3DatabasePermission)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3Role
	//
	D3RolePtr D3DatabasePermissionBase::GetD3Role()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3DatabasePermission_PR_D3Role);

		if (!pRelation)
			return NULL;

		return (D3RolePtr) pRelation->GetParent();
	}



	// Set parent of relation D3Role
	//
	void D3DatabasePermissionBase::SetD3Role(D3RolePtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3DatabasePermission_PR_D3Role), (EntityPtr) pParent);
	}



	// Get parent of relation D3MetaDatabase
	//
	D3MetaDatabasePtr D3DatabasePermissionBase::GetD3MetaDatabase()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3DatabasePermission_PR_D3MetaDatabase);

		if (!pRelation)
			return NULL;

		return (D3MetaDatabasePtr) pRelation->GetParent();
	}



	// Set parent of relation D3MetaDatabase
	//
	void D3DatabasePermissionBase::SetD3MetaDatabase(D3MetaDatabasePtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3DatabasePermission_PR_D3MetaDatabase), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3DatabasePermissionBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3DatabasePermissionPtr D3DatabasePermissionBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3DatabasePermissionPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3DatabasePermissionBase::iterator& D3DatabasePermissionBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
