// MODULE: D3EntityPermissionBase.cpp
//;
//; IMPLEMENTATION CLASS: D3EntityPermissionBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3EntityPermissionBase.h"

// Dependent includes
//
#include "D3MetaEntityBase.h"
#include "D3RoleBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3EntityPermissionBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3EntityPermissionBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3EntityPermissionBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3EntityPermission)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3EntityPermissionBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3EntityPermission)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3EntityPermissionPtr D3EntityPermissionBase::Load(DatabasePtr pDB, long lRoleID, long lMetaEntityID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3EntityPermission)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3EntityPermission_RoleID)->SetValue(lRoleID);
		tmpKey.GetColumn(D3MDDB_D3EntityPermission_MetaEntityID)->SetValue(lMetaEntityID);

		return (D3EntityPermissionPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3EntityPermission)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3Role
	//
	D3RolePtr D3EntityPermissionBase::GetD3Role()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3EntityPermission_PR_D3Role);

		if (!pRelation)
			return NULL;

		return (D3RolePtr) pRelation->GetParent();
	}



	// Set parent of relation D3Role
	//
	void D3EntityPermissionBase::SetD3Role(D3RolePtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3EntityPermission_PR_D3Role), (EntityPtr) pParent);
	}



	// Get parent of relation D3MetaEntity
	//
	D3MetaEntityPtr D3EntityPermissionBase::GetD3MetaEntity()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3EntityPermission_PR_D3MetaEntity);

		if (!pRelation)
			return NULL;

		return (D3MetaEntityPtr) pRelation->GetParent();
	}



	// Set parent of relation D3MetaEntity
	//
	void D3EntityPermissionBase::SetD3MetaEntity(D3MetaEntityPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3EntityPermission_PR_D3MetaEntity), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3EntityPermissionBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3EntityPermissionPtr D3EntityPermissionBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3EntityPermissionPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3EntityPermissionBase::iterator& D3EntityPermissionBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
