// MODULE: D3HistoricPasswordBase.cpp
//;
//; IMPLEMENTATION CLASS: D3HistoricPasswordBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3HistoricPasswordBase.h"

// Dependent includes
//
#include "D3UserBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3HistoricPasswordBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3HistoricPasswordBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3HistoricPasswordBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3HistoricPassword)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3HistoricPasswordBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3HistoricPassword)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3HistoricPasswordPtr D3HistoricPasswordBase::Load(DatabasePtr pDB, long lUserID, const D3Date& dPWDExpired, const Data& bPassword, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3HistoricPassword)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3HistoricPassword_UserID)->SetValue(lUserID);
		tmpKey.GetColumn(D3MDDB_D3HistoricPassword_PWDExpired)->SetValue(dPWDExpired);
		tmpKey.GetColumn(D3MDDB_D3HistoricPassword_Password)->SetValue(bPassword);

		return (D3HistoricPasswordPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3HistoricPassword)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3User
	//
	D3UserPtr D3HistoricPasswordBase::GetD3User()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3HistoricPassword_PR_D3User);

		if (!pRelation)
			return NULL;

		return (D3UserPtr) pRelation->GetParent();
	}



	// Set parent of relation D3User
	//
	void D3HistoricPasswordBase::SetD3User(D3UserPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3HistoricPassword_PR_D3User), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3HistoricPasswordBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3HistoricPasswordPtr D3HistoricPasswordBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3HistoricPasswordPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3HistoricPasswordBase::iterator& D3HistoricPasswordBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
