#ifndef _INC_D3HSDB_H_
#define _INC_D3HSDB_H_

// This header describes types for database D3HSDB and has been generated by D3.
//

// All declarations are inside the D3 namespace
//
namespace D3
{
	// Tables in this database
	//
	enum D3HSDB_Tables
	{
		D3HSDB_HSTopic,
		D3HSDB_HSTopicAssociation,
		D3HSDB_HSTopicLink,
		D3HSDB_HSResource,
		D3HSDB_HSResourceUsage,
		D3HSDB_HSMetaDatabaseTopic,
		D3HSDB_HSMetaEntityTopic,
		D3HSDB_HSMetaColumnTopic,
		D3HSDB_HSMetaKeyTopic,
		D3HSDB_HSMetaRelationTopic,
		D3HSDB_D3HSDBD3VI
	};

	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSTopic
	//

	// Specialisation: 
	//
	class HSTopic;
	typedef HSTopic*		HSTopicPtr;

	// Columns: 
	//
	enum D3HSDB_HSTopic_Columns
	{
		D3HSDB_HSTopic_ID,
		D3HSDB_HSTopic_Title,
		D3HSDB_HSTopic_MarkupText,
		D3HSDB_HSTopic_PlainText,
		D3HSDB_HSTopic_Targets
	};


	// Keys: 
	//
	enum D3HSDB_HSTopic_Keys
	{
		D3HSDB_HSTopic_PK_HSTopic,
		D3HSDB_HSTopic_SK_HSTopic
	};


	// Child relations: 
	//
	enum D3HSDB_HSTopic_ChildRelations
	{
		D3HSDB_HSTopic_CR_ChildTopics,
		D3HSDB_HSTopic_CR_ParentTopics,
		D3HSDB_HSTopic_CR_LinksToTopics,
		D3HSDB_HSTopic_CR_LinkedFromTopics,
		D3HSDB_HSTopic_CR_ResourceUsages,
		D3HSDB_HSTopic_CR_MetaDatabases,
		D3HSDB_HSTopic_CR_MetaEntities,
		D3HSDB_HSTopic_CR_MetaColumns,
		D3HSDB_HSTopic_CR_MetaKeys,
		D3HSDB_HSTopic_CR_MetaRelations
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSTopicAssociation
	//

	// Specialisation: 
	//
	class HSTopicAssociation;
	typedef HSTopicAssociation*		HSTopicAssociationPtr;

	// Columns: 
	//
	enum D3HSDB_HSTopicAssociation_Columns
	{
		D3HSDB_HSTopicAssociation_ParentTopicID,
		D3HSDB_HSTopicAssociation_ChildTopicID,
		D3HSDB_HSTopicAssociation_SequenceNo
	};


	// Keys: 
	//
	enum D3HSDB_HSTopicAssociation_Keys
	{
		D3HSDB_HSTopicAssociation_PK_HSTopicAssociation,
		D3HSDB_HSTopicAssociation_FK_HSTopicAssociation_ChildTopic
	};


	// Parent relations: 
	//
	enum D3HSDB_HSTopicAssociation_ParentRelations
	{
		D3HSDB_HSTopicAssociation_PR_ParentTopic,
		D3HSDB_HSTopicAssociation_PR_ChildTopic
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSTopicLink
	//

	// Specialisation: 
	//
	class HSTopicLink;
	typedef HSTopicLink*		HSTopicLinkPtr;

	// Columns: 
	//
	enum D3HSDB_HSTopicLink_Columns
	{
		D3HSDB_HSTopicLink_FromTopicID,
		D3HSDB_HSTopicLink_ToTopicID
	};


	// Keys: 
	//
	enum D3HSDB_HSTopicLink_Keys
	{
		D3HSDB_HSTopicLink_PK_HSTopicLink,
		D3HSDB_HSTopicLink_FK_HSTopicLink_ToTopic
	};


	// Parent relations: 
	//
	enum D3HSDB_HSTopicLink_ParentRelations
	{
		D3HSDB_HSTopicLink_PR_FromTopic,
		D3HSDB_HSTopicLink_PR_ToTopic
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSResource
	//

	// Specialisation: 
	//
	class HSResource;
	typedef HSResource*		HSResourcePtr;

	// Columns: 
	//
	enum D3HSDB_HSResource_Columns
	{
		D3HSDB_HSResource_ID,
		D3HSDB_HSResource_Name,
		D3HSDB_HSResource_Description,
		D3HSDB_HSResource_RawData,
		D3HSDB_HSResource_Type
	};


	// Keys: 
	//
	enum D3HSDB_HSResource_Keys
	{
		D3HSDB_HSResource_PK_HSResource,
		D3HSDB_HSResource_SK_HSResource
	};


	// Child relations: 
	//
	enum D3HSDB_HSResource_ChildRelations
	{
		D3HSDB_HSResource_CR_ResourceUsages
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSResourceUsage
	//

	// Specialisation: 
	//
	class HSResourceUsage;
	typedef HSResourceUsage*		HSResourceUsagePtr;

	// Columns: 
	//
	enum D3HSDB_HSResourceUsage_Columns
	{
		D3HSDB_HSResourceUsage_TopicID,
		D3HSDB_HSResourceUsage_ResourceID
	};


	// Keys: 
	//
	enum D3HSDB_HSResourceUsage_Keys
	{
		D3HSDB_HSResourceUsage_PK_HSResourceUsage,
		D3HSDB_HSResourceUsage_FK_HSResourceUsage_Resource
	};


	// Parent relations: 
	//
	enum D3HSDB_HSResourceUsage_ParentRelations
	{
		D3HSDB_HSResourceUsage_PR_Topic,
		D3HSDB_HSResourceUsage_PR_Resource
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSMetaDatabaseTopic
	//

	// Specialisation: 
	//
	class HSMetaDatabaseTopic;
	typedef HSMetaDatabaseTopic*		HSMetaDatabaseTopicPtr;

	// Columns: 
	//
	enum D3HSDB_HSMetaDatabaseTopic_Columns
	{
		D3HSDB_HSMetaDatabaseTopic_TopicID,
		D3HSDB_HSMetaDatabaseTopic_MetaDatabaseAlias
	};


	// Keys: 
	//
	enum D3HSDB_HSMetaDatabaseTopic_Keys
	{
		D3HSDB_HSMetaDatabaseTopic_PK_HSMetaDatabaseTopic,
		D3HSDB_HSMetaDatabaseTopic_FK_HSMetaDatabaseTopic_Topic
	};


	// Parent relations: 
	//
	enum D3HSDB_HSMetaDatabaseTopic_ParentRelations
	{
		D3HSDB_HSMetaDatabaseTopic_PR_Topic
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSMetaEntityTopic
	//

	// Specialisation: 
	//
	class HSMetaEntityTopic;
	typedef HSMetaEntityTopic*		HSMetaEntityTopicPtr;

	// Columns: 
	//
	enum D3HSDB_HSMetaEntityTopic_Columns
	{
		D3HSDB_HSMetaEntityTopic_TopicID,
		D3HSDB_HSMetaEntityTopic_MetaDatabaseAlias,
		D3HSDB_HSMetaEntityTopic_MetaEntityName
	};


	// Keys: 
	//
	enum D3HSDB_HSMetaEntityTopic_Keys
	{
		D3HSDB_HSMetaEntityTopic_PK_HSMetaEntityTopic,
		D3HSDB_HSMetaEntityTopic_FK_HSMetaEntityTopic_Topic
	};


	// Parent relations: 
	//
	enum D3HSDB_HSMetaEntityTopic_ParentRelations
	{
		D3HSDB_HSMetaEntityTopic_PR_Topic
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSMetaColumnTopic
	//

	// Specialisation: 
	//
	class HSMetaColumnTopic;
	typedef HSMetaColumnTopic*		HSMetaColumnTopicPtr;

	// Columns: 
	//
	enum D3HSDB_HSMetaColumnTopic_Columns
	{
		D3HSDB_HSMetaColumnTopic_TopicID,
		D3HSDB_HSMetaColumnTopic_MetaDatabaseAlias,
		D3HSDB_HSMetaColumnTopic_MetaEntityName,
		D3HSDB_HSMetaColumnTopic_MetaColumnName
	};


	// Keys: 
	//
	enum D3HSDB_HSMetaColumnTopic_Keys
	{
		D3HSDB_HSMetaColumnTopic_PK_HSMetaColumnTopic,
		D3HSDB_HSMetaColumnTopic_FK_HSMetaColumnTopic_Topic
	};


	// Parent relations: 
	//
	enum D3HSDB_HSMetaColumnTopic_ParentRelations
	{
		D3HSDB_HSMetaColumnTopic_PR_Topic
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSMetaKeyTopic
	//

	// Specialisation: 
	//
	class HSMetaKeyTopic;
	typedef HSMetaKeyTopic*		HSMetaKeyTopicPtr;

	// Columns: 
	//
	enum D3HSDB_HSMetaKeyTopic_Columns
	{
		D3HSDB_HSMetaKeyTopic_TopicID,
		D3HSDB_HSMetaKeyTopic_MetaDatabaseAlias,
		D3HSDB_HSMetaKeyTopic_MetaEntityName,
		D3HSDB_HSMetaKeyTopic_MetaKeyName
	};


	// Keys: 
	//
	enum D3HSDB_HSMetaKeyTopic_Keys
	{
		D3HSDB_HSMetaKeyTopic_PK_HSMetaKeyTopic,
		D3HSDB_HSMetaKeyTopic_FK_HSMetaKeyTopic_Topic
	};


	// Parent relations: 
	//
	enum D3HSDB_HSMetaKeyTopic_ParentRelations
	{
		D3HSDB_HSMetaKeyTopic_PR_Topic
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.HSMetaRelationTopic
	//

	// Specialisation: 
	//
	class HSMetaRelationTopic;
	typedef HSMetaRelationTopic*		HSMetaRelationTopicPtr;

	// Columns: 
	//
	enum D3HSDB_HSMetaRelationTopic_Columns
	{
		D3HSDB_HSMetaRelationTopic_TopicID,
		D3HSDB_HSMetaRelationTopic_MetaDatabaseAlias,
		D3HSDB_HSMetaRelationTopic_MetaEntityName,
		D3HSDB_HSMetaRelationTopic_MetaRelationName
	};


	// Keys: 
	//
	enum D3HSDB_HSMetaRelationTopic_Keys
	{
		D3HSDB_HSMetaRelationTopic_PK_HSMetaRelationTopic,
		D3HSDB_HSMetaRelationTopic_FK_HSMetaRelationTopic_Topic
	};


	// Parent relations: 
	//
	enum D3HSDB_HSMetaRelationTopic_ParentRelations
	{
		D3HSDB_HSMetaRelationTopic_PR_Topic
	};


	//-----------------------------------------------------------------------------
	// Table: D3HSDB.D3HSDBD3VI
	//

	// Columns: 
	//
	enum D3HSDB_D3HSDBD3VI_Columns
	{
		D3HSDB_D3HSDBD3VI_ID,
		D3HSDB_D3HSDBD3VI_Name,
		D3HSDB_D3HSDBD3VI_VersionMajor,
		D3HSDB_D3HSDBD3VI_VersionMinor,
		D3HSDB_D3HSDBD3VI_VersionRevision,
		D3HSDB_D3HSDBD3VI_LastUpdated
	};


	// Keys: 
	//
	enum D3HSDB_D3HSDBD3VI_Keys
	{
		D3HSDB_D3HSDBD3VI_PK_D3HSDBD3VI
	};

}		// namespace D3 ends here

#endif /* _INC_D3HSDB_H_ */
