#ifndef _INC_D3MDDB_H_
#define _INC_D3MDDB_H_

// This header describes types for database D3MDDB and has been generated by D3.
//

// All declarations are inside the D3 namespace
//
namespace D3
{
	// Tables in this database
	//
	enum D3MDDB_Tables
	{
		D3MDDB_D3MetaDatabase,
		D3MDDB_D3MetaEntity,
		D3MDDB_D3MetaColumn,
		D3MDDB_D3MetaColumnChoice,
		D3MDDB_D3MetaKey,
		D3MDDB_D3MetaKeyColumn,
		D3MDDB_D3MetaRelation,
		D3MDDB_D3Role,
		D3MDDB_D3User,
		D3MDDB_D3HistoricPassword,
		D3MDDB_D3RoleUser,
		D3MDDB_D3Session,
		D3MDDB_D3DatabasePermission,
		D3MDDB_D3EntityPermission,
		D3MDDB_D3ColumnPermission,
		D3MDDB_D3RowLevelPermission,
		D3MDDB_D3MDDBD3VI
	};

	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MetaDatabase
	//

	// Specialisation: 
	//
	class D3MetaDatabase;
	typedef D3MetaDatabase*		D3MetaDatabasePtr;

	// Columns: 
	//
	enum D3MDDB_D3MetaDatabase_Columns
	{
		D3MDDB_D3MetaDatabase_ID,
		D3MDDB_D3MetaDatabase_Alias,
		D3MDDB_D3MetaDatabase_VersionMajor,
		D3MDDB_D3MetaDatabase_VersionMinor,
		D3MDDB_D3MetaDatabase_VersionRevision,
		D3MDDB_D3MetaDatabase_InstanceInterface,
		D3MDDB_D3MetaDatabase_ProsaName,
		D3MDDB_D3MetaDatabase_Description,
		D3MDDB_D3MetaDatabase_Flags,
		D3MDDB_D3MetaDatabase_AccessRights
	};


	// Keys: 
	//
	enum D3MDDB_D3MetaDatabase_Keys
	{
		D3MDDB_D3MetaDatabase_PK_D3MetaDatabase,
		D3MDDB_D3MetaDatabase_SK_D3MetaDatabase
	};


	// Child relations: 
	//
	enum D3MDDB_D3MetaDatabase_ChildRelations
	{
		D3MDDB_D3MetaDatabase_CR_D3MetaEntities,
		D3MDDB_D3MetaDatabase_CR_D3RolePermissions
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MetaEntity
	//

	// Specialisation: 
	//
	class D3MetaEntity;
	typedef D3MetaEntity*		D3MetaEntityPtr;

	// Columns: 
	//
	enum D3MDDB_D3MetaEntity_Columns
	{
		D3MDDB_D3MetaEntity_ID,
		D3MDDB_D3MetaEntity_MetaDatabaseID,
		D3MDDB_D3MetaEntity_SequenceNo,
		D3MDDB_D3MetaEntity_Name,
		D3MDDB_D3MetaEntity_MetaClass,
		D3MDDB_D3MetaEntity_InstanceClass,
		D3MDDB_D3MetaEntity_InstanceInterface,
		D3MDDB_D3MetaEntity_JSMetaClass,
		D3MDDB_D3MetaEntity_JSInstanceClass,
		D3MDDB_D3MetaEntity_JSViewClass,
		D3MDDB_D3MetaEntity_JSDetailViewClass,
		D3MDDB_D3MetaEntity_ProsaName,
		D3MDDB_D3MetaEntity_Description,
		D3MDDB_D3MetaEntity_Alias,
		D3MDDB_D3MetaEntity_Flags,
		D3MDDB_D3MetaEntity_AccessRights
	};


	// Keys: 
	//
	enum D3MDDB_D3MetaEntity_Keys
	{
		D3MDDB_D3MetaEntity_PK_D3MetaEntity,
		D3MDDB_D3MetaEntity_SK_D3MetaEntity,
		D3MDDB_D3MetaEntity_CK_D3MetaEntity,
		D3MDDB_D3MetaEntity_FK_D3MetaEntity_MetaDatabaseID
	};


	// Parent relations: 
	//
	enum D3MDDB_D3MetaEntity_ParentRelations
	{
		D3MDDB_D3MetaEntity_PR_D3MetaDatabase
	};


	// Child relations: 
	//
	enum D3MDDB_D3MetaEntity_ChildRelations
	{
		D3MDDB_D3MetaEntity_CR_D3MetaColumns,
		D3MDDB_D3MetaEntity_CR_D3MetaKeys,
		D3MDDB_D3MetaEntity_CR_ChildD3MetaRelations,
		D3MDDB_D3MetaEntity_CR_D3RolePermissions,
		D3MDDB_D3MetaEntity_CR_D3RowLevelPermissions
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MetaColumn
	//

	// Specialisation: 
	//
	class D3MetaColumn;
	typedef D3MetaColumn*		D3MetaColumnPtr;

	// Columns: 
	//
	enum D3MDDB_D3MetaColumn_Columns
	{
		D3MDDB_D3MetaColumn_ID,
		D3MDDB_D3MetaColumn_MetaEntityID,
		D3MDDB_D3MetaColumn_SequenceNo,
		D3MDDB_D3MetaColumn_Name,
		D3MDDB_D3MetaColumn_ProsaName,
		D3MDDB_D3MetaColumn_Description,
		D3MDDB_D3MetaColumn_Type,
		D3MDDB_D3MetaColumn_Unit,
		D3MDDB_D3MetaColumn_FloatPrecision,
		D3MDDB_D3MetaColumn_MaxLength,
		D3MDDB_D3MetaColumn_Flags,
		D3MDDB_D3MetaColumn_AccessRights,
		D3MDDB_D3MetaColumn_MetaClass,
		D3MDDB_D3MetaColumn_InstanceClass,
		D3MDDB_D3MetaColumn_InstanceInterface,
		D3MDDB_D3MetaColumn_JSMetaClass,
		D3MDDB_D3MetaColumn_JSInstanceClass,
		D3MDDB_D3MetaColumn_JSViewClass,
		D3MDDB_D3MetaColumn_DefaultValue
	};


	// Keys: 
	//
	enum D3MDDB_D3MetaColumn_Keys
	{
		D3MDDB_D3MetaColumn_PK_D3MetaColumn,
		D3MDDB_D3MetaColumn_SK_D3MetaColumn,
		D3MDDB_D3MetaColumn_CK_D3MetaColumn,
		D3MDDB_D3MetaColumn_FK_D3MetaColumn_MetaEntityID
	};


	// Parent relations: 
	//
	enum D3MDDB_D3MetaColumn_ParentRelations
	{
		D3MDDB_D3MetaColumn_PR_D3MetaEntity
	};


	// Child relations: 
	//
	enum D3MDDB_D3MetaColumn_ChildRelations
	{
		D3MDDB_D3MetaColumn_CR_D3MetaKeyColumns,
		D3MDDB_D3MetaColumn_CR_D3MetaColumnChoices,
		D3MDDB_D3MetaColumn_CR_D3MetaRelationSwitches,
		D3MDDB_D3MetaColumn_CR_D3RolePermissions
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MetaColumnChoice
	//

	// Specialisation: 
	//
	class D3MetaColumnChoice;
	typedef D3MetaColumnChoice*		D3MetaColumnChoicePtr;

	// Columns: 
	//
	enum D3MDDB_D3MetaColumnChoice_Columns
	{
		D3MDDB_D3MetaColumnChoice_MetaColumnID,
		D3MDDB_D3MetaColumnChoice_SequenceNo,
		D3MDDB_D3MetaColumnChoice_ChoiceVal,
		D3MDDB_D3MetaColumnChoice_ChoiceDesc
	};


	// Keys: 
	//
	enum D3MDDB_D3MetaColumnChoice_Keys
	{
		D3MDDB_D3MetaColumnChoice_PK_D3MetaColumnChoice,
		D3MDDB_D3MetaColumnChoice_SK_D3MetaColumnChoice_Val,
		D3MDDB_D3MetaColumnChoice_SK_D3MetaColumnChoice_Desc
	};


	// Parent relations: 
	//
	enum D3MDDB_D3MetaColumnChoice_ParentRelations
	{
		D3MDDB_D3MetaColumnChoice_PR_D3MetaColumn
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MetaKey
	//

	// Specialisation: 
	//
	class D3MetaKey;
	typedef D3MetaKey*		D3MetaKeyPtr;

	// Columns: 
	//
	enum D3MDDB_D3MetaKey_Columns
	{
		D3MDDB_D3MetaKey_ID,
		D3MDDB_D3MetaKey_MetaEntityID,
		D3MDDB_D3MetaKey_SequenceNo,
		D3MDDB_D3MetaKey_Name,
		D3MDDB_D3MetaKey_ProsaName,
		D3MDDB_D3MetaKey_Description,
		D3MDDB_D3MetaKey_MetaClass,
		D3MDDB_D3MetaKey_InstanceClass,
		D3MDDB_D3MetaKey_JSMetaClass,
		D3MDDB_D3MetaKey_JSInstanceClass,
		D3MDDB_D3MetaKey_JSViewClass,
		D3MDDB_D3MetaKey_InstanceInterface,
		D3MDDB_D3MetaKey_Flags
	};


	// Keys: 
	//
	enum D3MDDB_D3MetaKey_Keys
	{
		D3MDDB_D3MetaKey_PK_D3MetaKey,
		D3MDDB_D3MetaKey_CK_D3MetaKey,
		D3MDDB_D3MetaKey_FK_D3MetaKey_MetaEntityID
	};


	// Parent relations: 
	//
	enum D3MDDB_D3MetaKey_ParentRelations
	{
		D3MDDB_D3MetaKey_PR_D3MetaEntity
	};


	// Child relations: 
	//
	enum D3MDDB_D3MetaKey_ChildRelations
	{
		D3MDDB_D3MetaKey_CR_D3MetaKeyColumns,
		D3MDDB_D3MetaKey_CR_ChildD3MetaRelations,
		D3MDDB_D3MetaKey_CR_ParentD3MetaRelations
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MetaKeyColumn
	//

	// Specialisation: 
	//
	class D3MetaKeyColumn;
	typedef D3MetaKeyColumn*		D3MetaKeyColumnPtr;

	// Columns: 
	//
	enum D3MDDB_D3MetaKeyColumn_Columns
	{
		D3MDDB_D3MetaKeyColumn_MetaKeyID,
		D3MDDB_D3MetaKeyColumn_SequenceNo,
		D3MDDB_D3MetaKeyColumn_MetaColumnID
	};


	// Keys: 
	//
	enum D3MDDB_D3MetaKeyColumn_Keys
	{
		D3MDDB_D3MetaKeyColumn_PK_D3MetaKeyColumn,
		D3MDDB_D3MetaKeyColumn_FK_D3MetaKeyColumn_MetaColumnID
	};


	// Parent relations: 
	//
	enum D3MDDB_D3MetaKeyColumn_ParentRelations
	{
		D3MDDB_D3MetaKeyColumn_PR_D3MetaColumn,
		D3MDDB_D3MetaKeyColumn_PR_D3MetaKey
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MetaRelation
	//

	// Specialisation: 
	//
	class D3MetaRelation;
	typedef D3MetaRelation*		D3MetaRelationPtr;

	// Columns: 
	//
	enum D3MDDB_D3MetaRelation_Columns
	{
		D3MDDB_D3MetaRelation_ID,
		D3MDDB_D3MetaRelation_ParentKeyID,
		D3MDDB_D3MetaRelation_ChildKeyID,
		D3MDDB_D3MetaRelation_ParentEntityID,
		D3MDDB_D3MetaRelation_SequenceNo,
		D3MDDB_D3MetaRelation_Name,
		D3MDDB_D3MetaRelation_ProsaName,
		D3MDDB_D3MetaRelation_Description,
		D3MDDB_D3MetaRelation_ReverseName,
		D3MDDB_D3MetaRelation_ReverseProsaName,
		D3MDDB_D3MetaRelation_ReverseDescription,
		D3MDDB_D3MetaRelation_MetaClass,
		D3MDDB_D3MetaRelation_InstanceClass,
		D3MDDB_D3MetaRelation_InstanceInterface,
		D3MDDB_D3MetaRelation_JSMetaClass,
		D3MDDB_D3MetaRelation_JSInstanceClass,
		D3MDDB_D3MetaRelation_JSParentViewClass,
		D3MDDB_D3MetaRelation_JSChildViewClass,
		D3MDDB_D3MetaRelation_Flags,
		D3MDDB_D3MetaRelation_SwitchColumnID,
		D3MDDB_D3MetaRelation_SwitchColumnValue
	};


	// Keys: 
	//
	enum D3MDDB_D3MetaRelation_Keys
	{
		D3MDDB_D3MetaRelation_PK_D3MetaRelation,
		D3MDDB_D3MetaRelation_SK_D3MetaRelation,
		D3MDDB_D3MetaRelation_CK_D3MetaRelation,
		D3MDDB_D3MetaRelation_FK_D3MetaRelation_ParentKeyID,
		D3MDDB_D3MetaRelation_FK_D3MetaRelation_ChildKeyID,
		D3MDDB_D3MetaRelation_FK_D3MetaRelation_SwitchColumnID
	};


	// Parent relations: 
	//
	enum D3MDDB_D3MetaRelation_ParentRelations
	{
		D3MDDB_D3MetaRelation_PR_ParentD3MetaEntity,
		D3MDDB_D3MetaRelation_PR_ParentD3MetaKey,
		D3MDDB_D3MetaRelation_PR_ChildD3MetaKey,
		D3MDDB_D3MetaRelation_PR_SwitchD3MetaColumn
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3Role
	//

	// Specialisation: 
	//
	class D3Role;
	typedef D3Role*		D3RolePtr;

	// Columns: 
	//
	enum D3MDDB_D3Role_Columns
	{
		D3MDDB_D3Role_ID,
		D3MDDB_D3Role_Name,
		D3MDDB_D3Role_Enabled,
		D3MDDB_D3Role_Features,
		D3MDDB_D3Role_IRSSettings,
		D3MDDB_D3Role_V3ParamSettings,
		D3MDDB_D3Role_T3ParamSettings,
		D3MDDB_D3Role_P3ParamSettings
	};


	// Keys: 
	//
	enum D3MDDB_D3Role_Keys
	{
		D3MDDB_D3Role_PK_D3Role,
		D3MDDB_D3Role_SK_D3Role
	};


	// Child relations: 
	//
	enum D3MDDB_D3Role_ChildRelations
	{
		D3MDDB_D3Role_CR_D3RoleUsers,
		D3MDDB_D3Role_CR_D3DatabasePermissions,
		D3MDDB_D3Role_CR_D3EntityPermissions,
		D3MDDB_D3Role_CR_D3ColumnPermissions
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3User
	//

	// Specialisation: 
	//
	class D3User;
	typedef D3User*		D3UserPtr;

	// Columns: 
	//
	enum D3MDDB_D3User_Columns
	{
		D3MDDB_D3User_ID,
		D3MDDB_D3User_Name,
		D3MDDB_D3User_Password,
		D3MDDB_D3User_Enabled,
		D3MDDB_D3User_WarehouseAreaAccessList,
		D3MDDB_D3User_CustomerAccessList,
		D3MDDB_D3User_TransmodeAccessList,
		D3MDDB_D3User_PWDAttempts,
		D3MDDB_D3User_PWDExpires,
		D3MDDB_D3User_Temporary,
		D3MDDB_D3User_Language
	};


	// Keys: 
	//
	enum D3MDDB_D3User_Keys
	{
		D3MDDB_D3User_PK_D3User,
		D3MDDB_D3User_SK_D3User
	};


	// Child relations: 
	//
	enum D3MDDB_D3User_ChildRelations
	{
		D3MDDB_D3User_CR_D3RoleUsers,
		D3MDDB_D3User_CR_D3RowLevelPermissions,
		D3MDDB_D3User_CR_D3HistoricPasswords
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3HistoricPassword
	//

	// Specialisation: 
	//
	class D3HistoricPassword;
	typedef D3HistoricPassword*		D3HistoricPasswordPtr;

	// Columns: 
	//
	enum D3MDDB_D3HistoricPassword_Columns
	{
		D3MDDB_D3HistoricPassword_UserID,
		D3MDDB_D3HistoricPassword_Password,
		D3MDDB_D3HistoricPassword_PWDExpired
	};


	// Keys: 
	//
	enum D3MDDB_D3HistoricPassword_Keys
	{
		D3MDDB_D3HistoricPassword_PK_D3HistoricPassword
	};


	// Parent relations: 
	//
	enum D3MDDB_D3HistoricPassword_ParentRelations
	{
		D3MDDB_D3HistoricPassword_PR_D3User
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3RoleUser
	//

	// Specialisation: 
	//
	class D3RoleUser;
	typedef D3RoleUser*		D3RoleUserPtr;

	// Columns: 
	//
	enum D3MDDB_D3RoleUser_Columns
	{
		D3MDDB_D3RoleUser_ID,
		D3MDDB_D3RoleUser_RoleID,
		D3MDDB_D3RoleUser_UserID
	};


	// Keys: 
	//
	enum D3MDDB_D3RoleUser_Keys
	{
		D3MDDB_D3RoleUser_PK_D3RoleUser,
		D3MDDB_D3RoleUser_SK_D3RoleUser,
		D3MDDB_D3RoleUser_FK_D3RoleUser_User
	};


	// Parent relations: 
	//
	enum D3MDDB_D3RoleUser_ParentRelations
	{
		D3MDDB_D3RoleUser_PR_D3Role,
		D3MDDB_D3RoleUser_PR_D3User
	};


	// Child relations: 
	//
	enum D3MDDB_D3RoleUser_ChildRelations
	{
		D3MDDB_D3RoleUser_CR_D3Sessions
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3Session
	//

	// Specialisation: 
	//
	class D3Session;
	typedef D3Session*		D3SessionPtr;

	// Columns: 
	//
	enum D3MDDB_D3Session_Columns
	{
		D3MDDB_D3Session_ID,
		D3MDDB_D3Session_RoleUserID,
		D3MDDB_D3Session_SignedIn,
		D3MDDB_D3Session_SignedOut
	};


	// Keys: 
	//
	enum D3MDDB_D3Session_Keys
	{
		D3MDDB_D3Session_PK_D3Session,
		D3MDDB_D3Session_FK_D3Session_RoleUser
	};


	// Parent relations: 
	//
	enum D3MDDB_D3Session_ParentRelations
	{
		D3MDDB_D3Session_PR_D3RoleUser
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3DatabasePermission
	//

	// Specialisation: 
	//
	class D3DatabasePermission;
	typedef D3DatabasePermission*		D3DatabasePermissionPtr;

	// Columns: 
	//
	enum D3MDDB_D3DatabasePermission_Columns
	{
		D3MDDB_D3DatabasePermission_RoleID,
		D3MDDB_D3DatabasePermission_MetaDatabaseID,
		D3MDDB_D3DatabasePermission_AccessRights
	};


	// Keys: 
	//
	enum D3MDDB_D3DatabasePermission_Keys
	{
		D3MDDB_D3DatabasePermission_PK_D3DatabasePermission,
		D3MDDB_D3DatabasePermission_FK_D3DatabasePermission_MetaDatabase
	};


	// Parent relations: 
	//
	enum D3MDDB_D3DatabasePermission_ParentRelations
	{
		D3MDDB_D3DatabasePermission_PR_D3Role,
		D3MDDB_D3DatabasePermission_PR_D3MetaDatabase
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3EntityPermission
	//

	// Specialisation: 
	//
	class D3EntityPermission;
	typedef D3EntityPermission*		D3EntityPermissionPtr;

	// Columns: 
	//
	enum D3MDDB_D3EntityPermission_Columns
	{
		D3MDDB_D3EntityPermission_RoleID,
		D3MDDB_D3EntityPermission_MetaEntityID,
		D3MDDB_D3EntityPermission_AccessRights
	};


	// Keys: 
	//
	enum D3MDDB_D3EntityPermission_Keys
	{
		D3MDDB_D3EntityPermission_PK_D3EntityPermission,
		D3MDDB_D3EntityPermission_FK_D3EntityPermission_MetaEntity
	};


	// Parent relations: 
	//
	enum D3MDDB_D3EntityPermission_ParentRelations
	{
		D3MDDB_D3EntityPermission_PR_D3Role,
		D3MDDB_D3EntityPermission_PR_D3MetaEntity
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3ColumnPermission
	//

	// Specialisation: 
	//
	class D3ColumnPermission;
	typedef D3ColumnPermission*		D3ColumnPermissionPtr;

	// Columns: 
	//
	enum D3MDDB_D3ColumnPermission_Columns
	{
		D3MDDB_D3ColumnPermission_RoleID,
		D3MDDB_D3ColumnPermission_MetaColumnID,
		D3MDDB_D3ColumnPermission_AccessRights
	};


	// Keys: 
	//
	enum D3MDDB_D3ColumnPermission_Keys
	{
		D3MDDB_D3ColumnPermission_PK_D3ColumnPermission,
		D3MDDB_D3ColumnPermission_FK_D3ColumnPermission_MetaColumn
	};


	// Parent relations: 
	//
	enum D3MDDB_D3ColumnPermission_ParentRelations
	{
		D3MDDB_D3ColumnPermission_PR_D3Role,
		D3MDDB_D3ColumnPermission_PR_D3MetaColumn
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3RowLevelPermission
	//

	// Specialisation: 
	//
	class D3RowLevelPermission;
	typedef D3RowLevelPermission*		D3RowLevelPermissionPtr;

	// Columns: 
	//
	enum D3MDDB_D3RowLevelPermission_Columns
	{
		D3MDDB_D3RowLevelPermission_UserID,
		D3MDDB_D3RowLevelPermission_MetaEntityID,
		D3MDDB_D3RowLevelPermission_AccessRights,
		D3MDDB_D3RowLevelPermission_PKValueList
	};


	// Keys: 
	//
	enum D3MDDB_D3RowLevelPermission_Keys
	{
		D3MDDB_D3RowLevelPermission_PK_D3RowLevelPermission,
		D3MDDB_D3RowLevelPermission_FK_D3RowLevelPermission_MetaEntity
	};


	// Parent relations: 
	//
	enum D3MDDB_D3RowLevelPermission_ParentRelations
	{
		D3MDDB_D3RowLevelPermission_PR_D3User,
		D3MDDB_D3RowLevelPermission_PR_D3MetaEntity
	};


	//-----------------------------------------------------------------------------
	// Table: D3MDDB.D3MDDBD3VI
	//

	// Columns: 
	//
	enum D3MDDB_D3MDDBD3VI_Columns
	{
		D3MDDB_D3MDDBD3VI_ID,
		D3MDDB_D3MDDBD3VI_Name,
		D3MDDB_D3MDDBD3VI_VersionMajor,
		D3MDDB_D3MDDBD3VI_VersionMinor,
		D3MDDB_D3MDDBD3VI_VersionRevision,
		D3MDDB_D3MDDBD3VI_LastUpdated
	};


	// Keys: 
	//
	enum D3MDDB_D3MDDBD3VI_Keys
	{
		D3MDDB_D3MDDBD3VI_PK_D3MDDBD3VI
	};

}		// namespace D3 ends here

#endif /* _INC_D3MDDB_H_ */
