// MODULE: D3MetaRelationBase.cpp
//;
//; IMPLEMENTATION CLASS: D3MetaRelationBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3MetaRelationBase.h"

// Dependent includes
//
#include "D3MetaColumnBase.h"
#include "D3MetaEntityBase.h"
#include "D3MetaKeyBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3MetaRelationBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3MetaRelationBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3MetaRelationBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaRelation)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3MetaRelationBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaRelation)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3MetaRelationPtr D3MetaRelationBase::Load(DatabasePtr pDB, long lID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaRelation)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3MetaRelation_ID)->SetValue(lID);

		return (D3MetaRelationPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaRelation)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation ParentD3MetaEntity
	//
	D3MetaEntityPtr D3MetaRelationBase::GetParentD3MetaEntity()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3MetaRelation_PR_ParentD3MetaEntity);

		if (!pRelation)
			return NULL;

		return (D3MetaEntityPtr) pRelation->GetParent();
	}



	// Set parent of relation ParentD3MetaEntity
	//
	void D3MetaRelationBase::SetParentD3MetaEntity(D3MetaEntityPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3MetaRelation_PR_ParentD3MetaEntity), (EntityPtr) pParent);
	}



	// Get parent of relation ParentD3MetaKey
	//
	D3MetaKeyPtr D3MetaRelationBase::GetParentD3MetaKey()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3MetaRelation_PR_ParentD3MetaKey);

		if (!pRelation)
			return NULL;

		return (D3MetaKeyPtr) pRelation->GetParent();
	}



	// Set parent of relation ParentD3MetaKey
	//
	void D3MetaRelationBase::SetParentD3MetaKey(D3MetaKeyPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3MetaRelation_PR_ParentD3MetaKey), (EntityPtr) pParent);
	}



	// Get parent of relation ChildD3MetaKey
	//
	D3MetaKeyPtr D3MetaRelationBase::GetChildD3MetaKey()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3MetaRelation_PR_ChildD3MetaKey);

		if (!pRelation)
			return NULL;

		return (D3MetaKeyPtr) pRelation->GetParent();
	}



	// Set parent of relation ChildD3MetaKey
	//
	void D3MetaRelationBase::SetChildD3MetaKey(D3MetaKeyPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3MetaRelation_PR_ChildD3MetaKey), (EntityPtr) pParent);
	}



	// Get parent of relation SwitchD3MetaColumn
	//
	D3MetaColumnPtr D3MetaRelationBase::GetSwitchD3MetaColumn()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3MetaRelation_PR_SwitchD3MetaColumn);

		if (!pRelation)
			return NULL;

		return (D3MetaColumnPtr) pRelation->GetParent();
	}



	// Set parent of relation SwitchD3MetaColumn
	//
	void D3MetaRelationBase::SetSwitchD3MetaColumn(D3MetaColumnPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3MetaRelation_PR_SwitchD3MetaColumn), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3MetaRelationBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3MetaRelationPtr D3MetaRelationBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3MetaRelationPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3MetaRelationBase::iterator& D3MetaRelationBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
