// MODULE: D3MetaKeyColumnBase.cpp
//;
//; IMPLEMENTATION CLASS: D3MetaKeyColumnBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3MetaKeyColumnBase.h"

// Dependent includes
//
#include "D3MetaColumnBase.h"
#include "D3MetaKeyBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3MetaKeyColumnBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3MetaKeyColumnBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3MetaKeyColumnBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaKeyColumn)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3MetaKeyColumnBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaKeyColumn)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3MetaKeyColumnPtr D3MetaKeyColumnBase::Load(DatabasePtr pDB, long lMetaKeyID, float fSequenceNo, long lMetaColumnID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaKeyColumn)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3MetaKeyColumn_MetaKeyID)->SetValue(lMetaKeyID);
		tmpKey.GetColumn(D3MDDB_D3MetaKeyColumn_SequenceNo)->SetValue(fSequenceNo);
		tmpKey.GetColumn(D3MDDB_D3MetaKeyColumn_MetaColumnID)->SetValue(lMetaColumnID);

		return (D3MetaKeyColumnPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaKeyColumn)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3MetaColumn
	//
	D3MetaColumnPtr D3MetaKeyColumnBase::GetD3MetaColumn()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3MetaKeyColumn_PR_D3MetaColumn);

		if (!pRelation)
			return NULL;

		return (D3MetaColumnPtr) pRelation->GetParent();
	}



	// Set parent of relation D3MetaColumn
	//
	void D3MetaKeyColumnBase::SetD3MetaColumn(D3MetaColumnPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3MetaKeyColumn_PR_D3MetaColumn), (EntityPtr) pParent);
	}



	// Get parent of relation D3MetaKey
	//
	D3MetaKeyPtr D3MetaKeyColumnBase::GetD3MetaKey()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3MetaKeyColumn_PR_D3MetaKey);

		if (!pRelation)
			return NULL;

		return (D3MetaKeyPtr) pRelation->GetParent();
	}



	// Set parent of relation D3MetaKey
	//
	void D3MetaKeyColumnBase::SetD3MetaKey(D3MetaKeyPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3MetaKeyColumn_PR_D3MetaKey), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3MetaKeyColumnBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3MetaKeyColumnPtr D3MetaKeyColumnBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3MetaKeyColumnPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3MetaKeyColumnBase::iterator& D3MetaKeyColumnBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
