// MODULE: D3MetaColumnChoiceBase.cpp
//;
//; IMPLEMENTATION CLASS: D3MetaColumnChoiceBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3MetaColumnChoiceBase.h"

// Dependent includes
//
#include "D3MetaColumnBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3MetaColumnChoiceBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3MetaColumnChoiceBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3MetaColumnChoiceBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaColumnChoice)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3MetaColumnChoiceBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaColumnChoice)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3MetaColumnChoicePtr D3MetaColumnChoiceBase::Load(DatabasePtr pDB, long lMetaColumnID, float fSequenceNo, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaColumnChoice)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3MetaColumnChoice_MetaColumnID)->SetValue(lMetaColumnID);
		tmpKey.GetColumn(D3MDDB_D3MetaColumnChoice_SequenceNo)->SetValue(fSequenceNo);

		return (D3MetaColumnChoicePtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaColumnChoice)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3MetaColumn
	//
	D3MetaColumnPtr D3MetaColumnChoiceBase::GetD3MetaColumn()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3MetaColumnChoice_PR_D3MetaColumn);

		if (!pRelation)
			return NULL;

		return (D3MetaColumnPtr) pRelation->GetParent();
	}



	// Set parent of relation D3MetaColumn
	//
	void D3MetaColumnChoiceBase::SetD3MetaColumn(D3MetaColumnPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3MetaColumnChoice_PR_D3MetaColumn), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3MetaColumnChoiceBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3MetaColumnChoicePtr D3MetaColumnChoiceBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3MetaColumnChoicePtr) pEntity;
	}



	// Assignment operator=()
	//
	D3MetaColumnChoiceBase::iterator& D3MetaColumnChoiceBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
