#ifndef INC_D3MetaColumnChoiceBase_H
#define INC_D3MetaColumnChoiceBase_H

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can gegenerate this file.
//
// The file declares methods which simplify client interactions with objects of type 
// D3MetaColumnChoice representing instances of D3MDDB.D3MetaColumnChoice.
//
//       For D3 to work correctly, you must implement your own class as follows:
//
//       #include "D3MetaColumnChoiceBase.h"
//
//       namespace D3
//       {
//         class D3MetaColumnChoice : public D3MetaColumnChoiceBase
//         {
//           D3_CLASS_DECL(D3MetaColumnChoice);
//
//           protected:
//             D3MetaColumnChoice() {}
//
//           public:
//             ~D3MetaColumnChoice() {}
//
//             // Insert your specialised member functions here...
//
//         };
//       } // end namespace D3
//

#include "Entity.h"
#include "Column.h"
#include "Key.h"
#include "Relation.h"
#include "D3MDDB.h"

namespace D3
{

	//! Use these enums to access columns through D3MetaColumnChoice::Column() method
	enum D3MetaColumnChoice_Fields
	{
		D3MetaColumnChoice_MetaColumnID,
		D3MetaColumnChoice_SequenceNo,
		D3MetaColumnChoice_ChoiceVal,
		D3MetaColumnChoice_ChoiceDesc
	};


	//! D3MetaColumnChoiceBase is a base class that \b MUST be subclassed through a class called \a D3MetaColumnChoice.
	/*! The purpose of this class to provide more natural access to related objects as well as this' columns.
			This class is only usefull if it is subclassed by a class called D3MetaColumnChoice
			Equally important is that the meta dictionary knows of the existence of your subclass as well as
			specialised Relation classes implemented herein. Only once these details have been added to the
			dictionary will D3 instantiate objects of type \a D3MetaColumnChoice representing rows from the table \a D3MDDB.D3MetaColumnChoice.
	*/
	class D3_API D3MetaColumnChoiceBase: public Entity
	{
		D3_CLASS_DECL(D3MetaColumnChoiceBase);

		public:
			//! Enable iterating over all instances of this
			class D3_API iterator : public InstanceKeyPtrSetItr
			{
				public:
					iterator() {}
					iterator(const InstanceKeyPtrSetItr& itr) : InstanceKeyPtrSetItr(itr) {}

					//! De-reference operator*()
					virtual D3MetaColumnChoicePtr   operator*();
					//! Assignment operator=()
					virtual iterator&               operator=(const iterator& itr);
			};

			static unsigned int                 size(DatabasePtr pDB)         { return GetAll(pDB)->size(); }
			static bool                         empty(DatabasePtr pDB)        { return GetAll(pDB)->empty(); }
			static iterator                     begin(DatabasePtr pDB)        { return iterator(GetAll(pDB)->begin()); }
			static iterator                     end(DatabasePtr pDB)          { return iterator(GetAll(pDB)->end()); }



		protected:
			D3MetaColumnChoiceBase() {}

		public:
			~D3MetaColumnChoiceBase() {}

			//! Create a new D3MetaColumnChoice
			static D3MetaColumnChoicePtr        CreateD3MetaColumnChoice(DatabasePtr pDB)		{ return (D3MetaColumnChoicePtr) pDB->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3MetaColumnChoice)->CreateInstance(pDB); }

			//! Return a collection of all instances of this
			static InstanceKeyPtrSetPtr					GetAll(DatabasePtr pDB);

			//! Load all instances of this
			static void													LoadAll(DatabasePtr pDB, bool bRefresh = false, bool bLazyFetch = true);

			//! Load a particular instance of this
			static D3MetaColumnChoicePtr        Load(DatabasePtr pDB, long lMetaColumnID, float fSequenceNo, bool bRefresh = false, bool bLazyFetch = true);

			//! Get related parent D3MetaColumn object
			virtual D3MetaColumnPtr             GetD3MetaColumn();
			//! Set related parent D3MetaColumn object
			virtual void												SetD3MetaColumn(D3MetaColumnPtr pD3MetaColumn);


			/*! @name Get Column Values
			    \note These accessors do not throw even if the column's value is NULL.
			           Therefore, you should use these methods only if you're sure the
			           column's value is NOT NULL before using these.
			*/
			//@{
			//! MetaColumnID
			virtual long                        GetMetaColumnID()              { return Column(D3MetaColumnChoice_MetaColumnID)->GetLong(); }
			//! SequenceNo
			virtual float                       GetSequenceNo()                { return Column(D3MetaColumnChoice_SequenceNo)->GetFloat(); }
			//! ChoiceVal
			virtual const std::string&          GetChoiceVal()                 { return Column(D3MetaColumnChoice_ChoiceVal)->GetString(); }
			//! ChoiceDesc
			virtual const std::string&          GetChoiceDesc()                { return Column(D3MetaColumnChoice_ChoiceDesc)->GetString(); }
			//@}

			/*! @name Set Column Values
			*/
			//@{
			//! Set MetaColumnID
			virtual bool												SetMetaColumnID(long val)      { return Column(D3MetaColumnChoice_MetaColumnID)->SetValue(val); }
			//! Set SequenceNo
			virtual bool												SetSequenceNo(float val)       { return Column(D3MetaColumnChoice_SequenceNo)->SetValue(val); }
			//! Set ChoiceVal
			virtual bool												SetChoiceVal(const std::string& val){ return Column(D3MetaColumnChoice_ChoiceVal)->SetValue(val); }
			//! Set ChoiceDesc
			virtual bool												SetChoiceDesc(const std::string& val){ return Column(D3MetaColumnChoice_ChoiceDesc)->SetValue(val); }
			//@}

			//! A column accessor provided mainly for backwards compatibility
			virtual ColumnPtr										Column(D3MetaColumnChoice_Fields eCol){ return Entity::GetColumn((unsigned int) eCol); }
	};



} // end namespace D3


#endif /* INC_D3MetaColumnChoiceBase_H */
