// MODULE: D3RowLevelPermissionBase.cpp
//;
//; IMPLEMENTATION CLASS: D3RowLevelPermissionBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3RowLevelPermissionBase.h"

// Dependent includes
//
#include "D3MetaEntityBase.h"
#include "D3UserBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3RowLevelPermissionBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3RowLevelPermissionBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3RowLevelPermissionBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RowLevelPermission)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3RowLevelPermissionBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RowLevelPermission)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3RowLevelPermissionPtr D3RowLevelPermissionBase::Load(DatabasePtr pDB, long lUserID, long lMetaEntityID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RowLevelPermission)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3RowLevelPermission_UserID)->SetValue(lUserID);
		tmpKey.GetColumn(D3MDDB_D3RowLevelPermission_MetaEntityID)->SetValue(lMetaEntityID);

		return (D3RowLevelPermissionPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RowLevelPermission)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3User
	//
	D3UserPtr D3RowLevelPermissionBase::GetD3User()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3RowLevelPermission_PR_D3User);

		if (!pRelation)
			return NULL;

		return (D3UserPtr) pRelation->GetParent();
	}



	// Set parent of relation D3User
	//
	void D3RowLevelPermissionBase::SetD3User(D3UserPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3RowLevelPermission_PR_D3User), (EntityPtr) pParent);
	}



	// Get parent of relation D3MetaEntity
	//
	D3MetaEntityPtr D3RowLevelPermissionBase::GetD3MetaEntity()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3RowLevelPermission_PR_D3MetaEntity);

		if (!pRelation)
			return NULL;

		return (D3MetaEntityPtr) pRelation->GetParent();
	}



	// Set parent of relation D3MetaEntity
	//
	void D3RowLevelPermissionBase::SetD3MetaEntity(D3MetaEntityPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3RowLevelPermission_PR_D3MetaEntity), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3RowLevelPermissionBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3RowLevelPermissionPtr D3RowLevelPermissionBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3RowLevelPermissionPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3RowLevelPermissionBase::iterator& D3RowLevelPermissionBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
