// MODULE: D3RoleUserBase.cpp
//;
//; IMPLEMENTATION CLASS: D3RoleUserBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3RoleUserBase.h"

// Dependent includes
//
#include "D3RoleBase.h"
#include "D3SessionBase.h"
#include "D3UserBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3RoleUserBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3RoleUserBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3RoleUserBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RoleUser)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3RoleUserBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RoleUser)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3RoleUserPtr D3RoleUserBase::Load(DatabasePtr pDB, long lID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RoleUser)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3RoleUser_ID)->SetValue(lID);

		return (D3RoleUserPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RoleUser)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3Role
	//
	D3RolePtr D3RoleUserBase::GetD3Role()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3RoleUser_PR_D3Role);

		if (!pRelation)
			return NULL;

		return (D3RolePtr) pRelation->GetParent();
	}



	// Set parent of relation D3Role
	//
	void D3RoleUserBase::SetD3Role(D3RolePtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3RoleUser_PR_D3Role), (EntityPtr) pParent);
	}



	// Get parent of relation D3User
	//
	D3UserPtr D3RoleUserBase::GetD3User()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3RoleUser_PR_D3User);

		if (!pRelation)
			return NULL;

		return (D3UserPtr) pRelation->GetParent();
	}



	// Set parent of relation D3User
	//
	void D3RoleUserBase::SetD3User(D3UserPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3RoleUser_PR_D3User), (EntityPtr) pParent);
	}



	// Load all instances of relation D3Sessions
	//
	void D3RoleUserBase::LoadAllD3Sessions(bool bRefresh, bool bLazyFetch)
	{
		RelationPtr		pRelation = NULL;

		pRelation = GetChildRelation(m_pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RoleUser)->GetChildMetaRelation(D3MDDB_D3RoleUser_CR_D3Sessions));

		if (pRelation)
			pRelation->LoadAll(bRefresh, bLazyFetch);
	}



	// Get the relation D3Sessions
	//
	D3RoleUserBase::D3Sessions* D3RoleUserBase::GetD3Sessions()
	{
		RelationPtr		pRelation;

		pRelation = GetChildRelation(m_pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3RoleUser)->GetChildMetaRelation(D3MDDB_D3RoleUser_CR_D3Sessions));

		return (D3RoleUserBase::D3Sessions*) pRelation;
	}





	// =====================================================================================
	// Class D3RoleUserBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3RoleUserPtr D3RoleUserBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3RoleUserPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3RoleUserBase::iterator& D3RoleUserBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}





	// =====================================================================================
	// Class D3RoleUserBase::D3Sessions
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3RoleUserBase::D3Sessions, Relation);

	// De-reference operator*()
	//
	D3SessionPtr D3RoleUserBase::D3Sessions::iterator::operator*()
	{
		return (D3SessionPtr) ((Relation::iterator*) this)->operator*();
	}



	// Assignment operator=()
	//
	D3RoleUserBase::D3Sessions::iterator& D3RoleUserBase::D3Sessions::iterator::operator=(const iterator& itr)
	{
		return (D3RoleUserBase::D3Sessions::iterator&) ((Relation::iterator*) this)->operator=(itr);
	}



	// front() method
	//
	D3SessionPtr D3RoleUserBase::D3Sessions::front()
	{
		return (D3SessionPtr) Relation::front();
	}



	// back() method
	//
	D3SessionPtr D3RoleUserBase::D3Sessions::back()
	{
		return (D3SessionPtr) Relation::back();
	}




} // end namespace D3
