// MODULE: D3SessionBase.cpp
//;
//; IMPLEMENTATION CLASS: D3SessionBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "D3SessionBase.h"

// Dependent includes
//
#include "D3RoleUserBase.h"


namespace D3
{

	// =====================================================================================
	// Class D3SessionBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(D3SessionBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr D3SessionBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3Session)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void D3SessionBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3Session)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	D3SessionPtr D3SessionBase::Load(DatabasePtr pDB, long lID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3MDDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3MDDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3Session)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3MDDB_D3Session_ID)->SetValue(lID);

		return (D3SessionPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3MDDB_D3Session)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation D3RoleUser
	//
	D3RoleUserPtr D3SessionBase::GetD3RoleUser()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3MDDB_D3Session_PR_D3RoleUser);

		if (!pRelation)
			return NULL;

		return (D3RoleUserPtr) pRelation->GetParent();
	}



	// Set parent of relation D3RoleUser
	//
	void D3SessionBase::SetD3RoleUser(D3RoleUserPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3MDDB_D3Session_PR_D3RoleUser), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class D3SessionBase::iterator Implementation
	//

	// De-reference operator*()
	//
	D3SessionPtr D3SessionBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (D3SessionPtr) pEntity;
	}



	// Assignment operator=()
	//
	D3SessionBase::iterator& D3SessionBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
