// MODULE: HSMetaEntityTopicBase.cpp
//;
//; IMPLEMENTATION CLASS: HSMetaEntityTopicBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "HSMetaEntityTopicBase.h"

// Dependent includes
//
#include "HSTopicBase.h"


namespace D3
{

	// =====================================================================================
	// Class HSMetaEntityTopicBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(HSMetaEntityTopicBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr HSMetaEntityTopicBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3HSDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3HSDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaEntityTopic)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void HSMetaEntityTopicBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3HSDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3HSDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaEntityTopic)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	HSMetaEntityTopicPtr HSMetaEntityTopicBase::Load(DatabasePtr pDB, const std::string& strMetaDatabaseAlias, const std::string& strMetaEntityName, long lTopicID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3HSDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3HSDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaEntityTopic)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3HSDB_HSMetaEntityTopic_MetaDatabaseAlias)->SetValue(strMetaDatabaseAlias);
		tmpKey.GetColumn(D3HSDB_HSMetaEntityTopic_MetaEntityName)->SetValue(strMetaEntityName);
		tmpKey.GetColumn(D3HSDB_HSMetaEntityTopic_TopicID)->SetValue(lTopicID);

		return (HSMetaEntityTopicPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaEntityTopic)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation Topic
	//
	HSTopicPtr HSMetaEntityTopicBase::GetTopic()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3HSDB_HSMetaEntityTopic_PR_Topic);

		if (!pRelation)
			return NULL;

		return (HSTopicPtr) pRelation->GetParent();
	}



	// Set parent of relation Topic
	//
	void HSMetaEntityTopicBase::SetTopic(HSTopicPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3HSDB_HSMetaEntityTopic_PR_Topic), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class HSMetaEntityTopicBase::iterator Implementation
	//

	// De-reference operator*()
	//
	HSMetaEntityTopicPtr HSMetaEntityTopicBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (HSMetaEntityTopicPtr) pEntity;
	}



	// Assignment operator=()
	//
	HSMetaEntityTopicBase::iterator& HSMetaEntityTopicBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
