// MODULE: HSMetaKeyTopicBase.cpp
//;
//; IMPLEMENTATION CLASS: HSMetaKeyTopicBase
//;

// WARNING: This file has been generated by D3. You should NEVER change this file.
//          Please refer to the documentation of MetaEntity::CreateSpecialisedCPPHeader()
//          which explains in detail how you can regenerate this file.
//

#include "D3Types.h"

#include "HSMetaKeyTopicBase.h"

// Dependent includes
//
#include "HSTopicBase.h"


namespace D3
{

	// =====================================================================================
	// Class HSMetaKeyTopicBase Implementation
	//

	// D3 class factory support for this class
	//
	D3_CLASS_IMPL(HSMetaKeyTopicBase, Entity);


	// Get a collection reflecting all currently resident instances of this
	//
	/* static */
	InstanceKeyPtrSetPtr HSMetaKeyTopicBase::GetAll(DatabasePtr pDB)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3HSDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3HSDB"));

		if (!pDatabase)
			return NULL;

		return pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaKeyTopic)->GetPrimaryMetaKey()->GetInstanceKeySet(pDatabase);
	}



	// Make all objects of this type memory resident
	//
	/* static */
	void HSMetaKeyTopicBase::LoadAll(DatabasePtr pDB, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3HSDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3HSDB"));

		if (!pDatabase)
			return;

		pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaKeyTopic)->LoadAll(pDatabase, bRefresh, bLazyFetch);
	}



	// Make a specific instance resident
	//
	/* static */
	HSMetaKeyTopicPtr HSMetaKeyTopicBase::Load(DatabasePtr pDB, const std::string& strMetaDatabaseAlias, const std::string& strMetaEntityName, const std::string& strMetaKeyName, long lTopicID, bool bRefresh, bool bLazyFetch)
	{
		DatabasePtr		pDatabase = pDB;


		if (!pDatabase)
			return NULL;

		if (pDatabase->GetMetaDatabase() != MetaDatabase::GetMetaDatabase("D3HSDB"))
			pDatabase = pDatabase->GetDatabaseWorkspace()->GetDatabase(MetaDatabase::GetMetaDatabase("D3HSDB"));

		if (!pDatabase)
			return NULL;

		TemporaryKey	tmpKey(*(pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaKeyTopic)->GetPrimaryMetaKey()));

		// Set all key column values
		//
		tmpKey.GetColumn(D3HSDB_HSMetaKeyTopic_MetaDatabaseAlias)->SetValue(strMetaDatabaseAlias);
		tmpKey.GetColumn(D3HSDB_HSMetaKeyTopic_MetaEntityName)->SetValue(strMetaEntityName);
		tmpKey.GetColumn(D3HSDB_HSMetaKeyTopic_MetaKeyName)->SetValue(strMetaKeyName);
		tmpKey.GetColumn(D3HSDB_HSMetaKeyTopic_TopicID)->SetValue(lTopicID);

		return (HSMetaKeyTopicPtr) pDatabase->GetMetaDatabase()->GetMetaEntity(D3HSDB_HSMetaKeyTopic)->GetPrimaryMetaKey()->LoadObject(&tmpKey, pDatabase, bRefresh, bLazyFetch);
	}



	// Get parent of relation Topic
	//
	HSTopicPtr HSMetaKeyTopicBase::GetTopic()
	{
		RelationPtr		pRelation;

		pRelation = GetParentRelation(D3HSDB_HSMetaKeyTopic_PR_Topic);

		if (!pRelation)
			return NULL;

		return (HSTopicPtr) pRelation->GetParent();
	}



	// Set parent of relation Topic
	//
	void HSMetaKeyTopicBase::SetTopic(HSTopicPtr pParent)
	{
		SetParent(m_pMetaEntity->GetParentMetaRelation(D3HSDB_HSMetaKeyTopic_PR_Topic), (EntityPtr) pParent);
	}





	// =====================================================================================
	// Class HSMetaKeyTopicBase::iterator Implementation
	//

	// De-reference operator*()
	//
	HSMetaKeyTopicPtr HSMetaKeyTopicBase::iterator::operator*()
	{
		InstanceKeyPtr pKey;
		EntityPtr      pEntity;

		pKey = (InstanceKeyPtr) ((InstanceKeyPtrSetItr*) this)->operator*();
		pEntity = pKey->GetEntity();

		return (HSMetaKeyTopicPtr) pEntity;
	}



	// Assignment operator=()
	//
	HSMetaKeyTopicBase::iterator& HSMetaKeyTopicBase::iterator::operator=(const iterator& itr)
	{
		((InstanceKeyPtrSetItr*) this)->operator=(itr);

		return *this;
	}




} // end namespace D3
